#ifndef COLONYUTILS_GLOBAL_HPP
#define COLONYUTILS_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(COLONYUTILS_LIBRARY)
#  define COLONYUTILSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COLONYUTILSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COLONYUTILS_GLOBAL_HPP
